# Generated by Django 5.0.6 on 2024-05-14 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0003_alter_profile_email_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.CharField(max_length=100)),
                ('voice_id_name', models.CharField(max_length=100)),
                ('file_url', models.URLField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voices', to='base.profile')),
            ],
        ),
    ]
