# Generated by Django 5.0.6 on 2024-05-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='api_key',
            field=models.CharField(default='63cb3ad2b580a642e46a1a5ce9ca26ea', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voice',
            name='api_key_mapped',
            field=models.CharField(default='0XepuiUjjgtpgZtAonMPfuLkYGGuLEE8', max_length=200),
            preserve_default=False,
        ),
    ]
