# Generated by Django 5.0.6 on 2024-05-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_profile_email_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='api_key',
            field=models.CharField(default='63cb3ad2b580a642e46a1a5ce9ca26ea', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='api_key_mapped',
            field=models.CharField(default='cZ0UAFARbq79k31XWH5uLmSk3vGMSUcc', max_length=200),
            preserve_default=False,
        ),
    ]
